# ACFS Installer Change Notification Workflow
#
# This workflow notifies the ACFS repository when installer scripts change.
# It should be added to any /dp project that has an installer script tracked
# in ACFS's checksums.yaml.
#
# Setup:
# 1. Copy this file to .github/workflows/notify-acfs.yml
# 2. Create a repository secret ACFS_NOTIFY_TOKEN with a GitHub PAT
#    that has repo scope for Dicklesworthstone/agentic_coding_flywheel_setup
# 3. Update TOOL_NAME to match the entry in ACFS checksums.yaml
#
# Testing:
# - Push a change to the installer script and check Actions logs
# - Use workflow_dispatch with dry_run: true to test without sending

name: Notify ACFS of Installer Changes

on:
  push:
    branches: [main, master]
    paths:
      - 'install.sh'
      - 'scripts/install.sh'
      - 'installer/**'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Test without sending notification'
        required: false
        default: 'false'
        type: boolean
      force:
        description: 'Force notification even if checksum unchanged'
        required: false
        default: 'false'
        type: boolean

env:
  # REQUIRED: Update this to match your entry in ACFS checksums.yaml
  TOOL_NAME: '{{ TOOL_NAME_PLACEHOLDER }}'

  # Path to installer script (update if different)
  INSTALLER_PATH: 'install.sh'

  # ACFS repository to notify
  ACFS_REPO: 'Dicklesworthstone/agentic_coding_flywheel_setup'

jobs:
  compute-and-notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      sha256: ${{ steps.checksum.outputs.sha256 }}
      changed: ${{ steps.compare.outputs.changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need previous commit for comparison

      - name: Validate installer exists
        id: validate
        run: |
          if [[ ! -f "${{ env.INSTALLER_PATH }}" ]]; then
            echo "::error::Installer not found at ${{ env.INSTALLER_PATH }}"
            exit 1
          fi
          echo "installer_size=$(stat -c%s "${{ env.INSTALLER_PATH }}")" >> $GITHUB_OUTPUT

      - name: Compute SHA256 checksum
        id: checksum
        run: |
          SHA256=$(sha256sum "${{ env.INSTALLER_PATH }}" | cut -d' ' -f1)
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
          echo "Computed SHA256: $SHA256"

      - name: Get previous checksum (if available)
        id: previous
        run: |
          if git show HEAD~1:"${{ env.INSTALLER_PATH }}" > /tmp/previous_installer 2>/dev/null; then
            PREV_SHA256=$(sha256sum /tmp/previous_installer | cut -d' ' -f1)
            echo "prev_sha256=$PREV_SHA256" >> $GITHUB_OUTPUT
            echo "Previous SHA256: $PREV_SHA256"
          else
            echo "prev_sha256=none" >> $GITHUB_OUTPUT
            echo "No previous version found"
          fi

      - name: Compare checksums
        id: compare
        run: |
          if [[ "${{ steps.checksum.outputs.sha256 }}" != "${{ steps.previous.outputs.prev_sha256 }}" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Checksum changed, will notify ACFS"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "Checksum unchanged"
          fi

      - name: Prepare notification payload
        id: payload
        if: steps.compare.outputs.changed == 'true' || github.event.inputs.force == 'true'
        run: |
          PAYLOAD=$(jq -n \
            --arg tool "${{ env.TOOL_NAME }}" \
            --arg new_sha256 "${{ steps.checksum.outputs.sha256 }}" \
            --arg old_sha256 "${{ steps.previous.outputs.prev_sha256 }}" \
            --arg commit_sha "${{ github.sha }}" \
            --arg commit_message "${{ github.event.head_commit.message }}" \
            --arg repo "${{ github.repository }}" \
            --arg branch "${{ github.ref_name }}" \
            --arg actor "${{ github.actor }}" \
            --arg installer_path "${{ env.INSTALLER_PATH }}" \
            --arg installer_size "${{ steps.validate.outputs.installer_size }}" \
            --arg run_id "${{ github.run_id }}" \
            '{
              tool: $tool,
              new_sha256: $new_sha256,
              old_sha256: $old_sha256,
              commit: {
                sha: $commit_sha,
                message: ($commit_message | split("\n")[0]),
                repo: $repo,
                branch: $branch,
                actor: $actor
              },
              installer: {
                path: $installer_path,
                size_bytes: ($installer_size | tonumber)
              },
              workflow_run_id: $run_id,
              timestamp: (now | todate)
            }')
          echo "payload<<EOF" >> $GITHUB_OUTPUT
          echo "$PAYLOAD" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Payload prepared:"
          echo "$PAYLOAD" | jq .

      - name: Send notification to ACFS (dry run)
        if: |
          (steps.compare.outputs.changed == 'true' || github.event.inputs.force == 'true') &&
          github.event.inputs.dry_run == 'true'
        run: |
          echo "::notice::DRY RUN - Would send notification to ACFS"
          echo "Event type: installer-updated"
          echo "Payload:"
          echo '${{ steps.payload.outputs.payload }}' | jq .

      - name: Send notification to ACFS
        if: |
          (steps.compare.outputs.changed == 'true' || github.event.inputs.force == 'true') &&
          github.event.inputs.dry_run != 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACFS_NOTIFY_TOKEN }}
          repository: ${{ env.ACFS_REPO }}
          event-type: installer-updated
          client-payload: ${{ steps.payload.outputs.payload }}

      - name: Log result
        if: always()
        run: |
          echo "## Notification Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Field | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Tool | ${{ env.TOOL_NAME }} |" >> $GITHUB_STEP_SUMMARY
          echo "| SHA256 | \`${{ steps.checksum.outputs.sha256 }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Changed | ${{ steps.compare.outputs.changed }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Dry Run | ${{ github.event.inputs.dry_run || 'false' }} |" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ steps.compare.outputs.changed }}" == "true" ]]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Notification sent to ACFS" >> $GITHUB_STEP_SUMMARY
          else
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "No notification sent (checksum unchanged)" >> $GITHUB_STEP_SUMMARY
          fi

  # Optional: Add this job for when an installer is being deprecated
  notify-removal:
    if: github.event_name == 'delete' || contains(github.event.head_commit.message, '[remove-installer]')
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACFS_NOTIFY_TOKEN }}
          repository: Dicklesworthstone/agentic_coding_flywheel_setup
          event-type: installer-removed
          client-payload: |
            {
              "tool": "${{ env.TOOL_NAME }}",
              "commit_sha": "${{ github.sha }}",
              "repo": "${{ github.repository }}",
              "reason": "Installer deprecated or removed"
            }
