# ACFS Integration Validation Workflow
#
# Run this workflow to validate that the ACFS notification integration
# is set up correctly in your repository.
#
# Usage:
#   gh workflow run validate-acfs.yml

name: Validate ACFS Integration

on:
  workflow_dispatch:

env:
  # Must match the value in notify-acfs.yml
  TOOL_NAME: '{{ TOOL_NAME_PLACEHOLDER }}'
  INSTALLER_PATH: 'install.sh'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check installer exists
        run: |
          if [[ ! -f "${{ env.INSTALLER_PATH }}" ]]; then
            echo "::error::Installer not found at ${{ env.INSTALLER_PATH }}"
            exit 1
          fi
          echo "Installer found at ${{ env.INSTALLER_PATH }}"
          echo "Size: $(stat -c%s "${{ env.INSTALLER_PATH }}") bytes"
          echo "SHA256: $(sha256sum "${{ env.INSTALLER_PATH }}" | cut -d' ' -f1)"

      - name: Check ACFS_NOTIFY_TOKEN secret
        env:
          TOKEN: ${{ secrets.ACFS_NOTIFY_TOKEN }}
        run: |
          if [[ -z "$TOKEN" ]]; then
            echo "::error::ACFS_NOTIFY_TOKEN secret is not set"
            echo "Go to Settings > Secrets > Actions and create ACFS_NOTIFY_TOKEN"
            exit 1
          fi
          echo "ACFS_NOTIFY_TOKEN secret is configured"

      - name: Validate token has repo scope
        env:
          GH_TOKEN: ${{ secrets.ACFS_NOTIFY_TOKEN }}
        run: |
          if ! gh api /repos/Dicklesworthstone/agentic_coding_flywheel_setup > /dev/null 2>&1; then
            echo "::error::Token does not have access to ACFS repository"
            echo "Ensure the PAT has 'repo' scope for Dicklesworthstone/agentic_coding_flywheel_setup"
            exit 1
          fi
          echo "Token has access to ACFS repository"

      - name: Check tool is in checksums.yaml
        run: |
          CHECKSUMS=$(curl -sL "https://raw.githubusercontent.com/Dicklesworthstone/agentic_coding_flywheel_setup/main/checksums.yaml")
          if ! echo "$CHECKSUMS" | grep -q "${{ env.TOOL_NAME }}:"; then
            echo "::warning::Tool '${{ env.TOOL_NAME }}' not found in ACFS checksums.yaml"
            echo "You may need to add it first, or verify the TOOL_NAME matches exactly"
          else
            echo "Tool '${{ env.TOOL_NAME }}' found in ACFS checksums.yaml"

            # Extract and display the current checksum from ACFS
            ACFS_SHA256=$(echo "$CHECKSUMS" | grep -A2 "${{ env.TOOL_NAME }}:" | grep "sha256:" | awk '{print $2}' | tr -d '"')
            LOCAL_SHA256=$(sha256sum "${{ env.INSTALLER_PATH }}" | cut -d' ' -f1)

            echo ""
            echo "Checksum comparison:"
            echo "  ACFS:  $ACFS_SHA256"
            echo "  Local: $LOCAL_SHA256"

            if [[ "$ACFS_SHA256" == "$LOCAL_SHA256" ]]; then
              echo "  Status: Checksums match"
            else
              echo "  Status: Checksums differ (notification will be sent on next push)"
            fi
          fi

      - name: Check notify-acfs workflow exists
        run: |
          if [[ ! -f ".github/workflows/notify-acfs.yml" ]]; then
            echo "::warning::notify-acfs.yml workflow not found"
            echo "Copy templates/notify-acfs-workflow.yml to .github/workflows/notify-acfs.yml"
          else
            echo "notify-acfs.yml workflow is present"
          fi

      - name: Summary
        run: |
          echo "## ACFS Integration Validation" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Installer exists | Pass |" >> $GITHUB_STEP_SUMMARY
          echo "| ACFS_NOTIFY_TOKEN | Pass |" >> $GITHUB_STEP_SUMMARY
          echo "| Token has access | Pass |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All validation checks passed" >> $GITHUB_STEP_SUMMARY
